AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates dynamodb resources"

Resources:
  DdbTableUsage:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "hash_key"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "hash_key"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: "myperistentstore"
      Tags:
        - Key: Env
          Value: "Production"