AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
Parameters: 
  TableNameParameter: 
    Type: String
Resources:
  tictactoeapiendpoint:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: "api/user/handler.invoke"
      Runtime: "nodejs8.10"
      CodeUri: .
      Description: >-
        "A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway."
      MemorySize: 512
      Timeout: 20
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableNameParameter
      Events:
        Api1:
          Type: "Api"
          Properties:
            Path: "/api/info/{user}""
            Method: "post"